name: poetry_build

on:
  workflow_call:
    inputs:
      pypi_package:
        required: true
        type: string

jobs:
  check-tomal-version:
    uses: ./.github/workflows/check_tomal.yaml
    with:
        pypi_package: ${{ inputs.pypi_package }}

  build:
    needs: check-tomal-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Poetry
        run: pip install poetry

      - name: Build pypi package package
        run: poetry build
